name: Update dart-sass

on:
  schedule:
    - cron: '30 5 * * *'
  workflow_dispatch:

jobs:
  check-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check newer version
        id: version-check
        run: |
          current_version=$(grep -P '(?<=<Version>).+(?=</Version>)' -o AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj)
          latest_version=$(curl -s https://api.github.com/repos/sass/dart-sass/releases/latest | jq '.tag_name' -r)

          function version { echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'; }

          echo "Current version: $current_version"
          echo "Latest version: $latest_version"

          if [ $(version $latest_version) -gt $(version $current_version) ]; then
            echo "Found newer version of dart-sass: $latest_version"

            if ! git branch -a | grep "dart-sass/$latest_version" >/dev/null ; then
              echo ::set-output name=sass-version::${latest_version}
            else
              echo "A branch already exists for this version, skipping"
            fi
          fi
      - name: Install dependencies
        if: success() && steps.version-check.outputs.sass-version != ''
        env:
          SASS_VERSION: ${{ steps.version-check.outputs.sass-version }}
        run: |
          curl -sL -o dart-sass-linux.tar.gz "https://github.com/sass/dart-sass/releases/download/$SASS_VERSION/dart-sass-$SASS_VERSION-linux-x64.tar.gz"
          curl -sL -o dart-sass-macos.tar.gz "https://github.com/sass/dart-sass/releases/download/$SASS_VERSION/dart-sass-$SASS_VERSION-macos-x64.tar.gz"
          curl -sL -o dart-sass-windows.zip "https://github.com/sass/dart-sass/releases/download/$SASS_VERSION/dart-sass-$SASS_VERSION-windows-x64.zip"

          rm -rf AspNetCore.SassCompiler/runtimes/{linux,osx,win}-x64/*

          tar xf dart-sass-linux.tar.gz
          mv dart-sass/* AspNetCore.SassCompiler/runtimes/linux-x64
          rm -rf dart-sass

          tar xf dart-sass-macos.tar.gz
          mv dart-sass/* AspNetCore.SassCompiler/runtimes/osx-x64
          rm -rf dart-sass

          unzip dart-sass-windows.zip
          mv dart-sass/* AspNetCore.SassCompiler/runtimes/win-x64
          rm -rf dart-sass

          rm dart-sass-*

          perl -pi -e "s/(?<=<Version>).+(?=<\/Version>)/$SASS_VERSION/g" AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj

      - name: Create Pull Request
        if: success() && steps.version-check.outputs.sass-version != ''
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update dart-sass to ${{ steps.version-check.outputs.sass-version }}
          branch: dart-sass/${{ steps.version-check.outputs.sass-version }}
          delete-branch: true
          title: Update dart-sass to ${{ steps.version-check.outputs.sass-version }}
          body: |
            Update dart-sass to ${{ steps.version-check.outputs.sass-version }}

            **Note**: This is an autogenerated PR.
